REQ-403 add module to split PEM files
xapi-project/xen-api pull request #4245
Opened 2020-10-30 15:52 UTC by lindig

Add a module to split a PEM file into its components and return them as
strings.

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

2020-10-30 16:04 UTC, psafont approved these changes
Tests cases make it very easy to  check the correctness of the code, they look comprehensive to me.

2020-11-02 11:52 UTC, psafont approved these changes

2020-11-02 14:54 UTC, lippirk approved these changes

2020-11-02 15:17 UTC, psafont requested changes

2020-11-02 15:17 UTC, psafont commented on ocaml/xapi/xapi_globs.ml
> +let stunnel_cert_path = ref "/etc/stunnel/xapi-stunnel-ca-bundle.pem"
```suggestion
let stunnel_ca_cert_bundle_path = ref "/etc/stunnel/xapi-stunnel-ca-bundle.pem"
let stunnel_ca_certs_path = ref "/etc/stunnel/certs"
```
There are actually two paths for ca certificates, one pem file containing all ca certs, and one directory with a file per certificate.

2020-11-02 15:24 UTC, lindig commented on ocaml/xapi/xapi_globs.ml
> +let stunnel_cert_path = ref "/etc/stunnel/xapi-stunnel-ca-bundle.pem"
I think it would be better to deal only with one source of truth - either the PEM or the individual files

2020-11-02 15:29 UTC, psafont commented on ocaml/xapi/xapi_globs.ml
> +let stunnel_cert_path = ref "/etc/stunnel/xapi-stunnel-ca-bundle.pem"
I will check if stunnel supports reading from a directory instead of a single pem file.
Handling certificates as files is convenient for installing and removing individual certificates because they have individual filenames. This is exploited by the current interface and I was thinking of exploiting it to keep them in sync with the database.

2020-11-02 15:34 UTC, lippirk commented on ocaml/xapi/xapi_globs.ml
> +let stunnel_cert_path = ref "/etc/stunnel/xapi-stunnel-ca-bundle.pem"
I would suggest that we avoid duplicating this path (it's defined here, though not exposed via the mli yet https://github.com/xapi-project/xen-api-libs-transitional/blob/dc2e8d18f650f801744e099e94847adf4410cab7/stunnel/stunnel.ml#L27)

I would agree with Christian, and suggest that we use only one. If we were to use two, then we have to pass two parameters to stunnel (`CApath` and `CAfile`), but it's not obvious which one would take precedence

2020-11-02 15:52 UTC, lindig commented on ocaml/xapi/xapi_globs.ml
> +let stunnel_cert_path = ref "/etc/stunnel/xapi-stunnel-ca-bundle.pem"
I updated it to use the directory as global configuration paramete.

2020-11-02 16:07 UTC, psafont approved these changes

2020-11-02 16:11 UTC, merged