CP-36099 add host_internal cert type to db schema
xapi-project/xen-api pull request #4355
Opened 2021-03-26 16:44 UTC by lippirk

2021-03-26 17:00 UTC, psafont commented
Adding some code to output red text for the hash check would help see it:

```
New schema hash ('0ab12bc6f78eeae82a987239b4b100a7') doesn't match the last known one. Please bump the
datamodel schema versions if necessary, and update 'last_known_schema_hash'.
```

`\033[31;1mRED TEXT\033[0m NORMAL TEXT`

2021-03-30 14:45 UTC, psafont requested changes
I think `ocaml/alerts/certificate/certificate_check.ml` should be changed as well to not delete alerts that affect `host_internal certificates (easiest way is probably to change `messages_in_host` (line 57) to filter by message name, just like records are filtered in 91-96)

2021-03-31 16:01 UTC, psafont approved these changes

2021-04-09 15:16 UTC, lindig approved these changes

2021-04-09 15:18 UTC, merged