CA-361151: Provide default user details on ldap query fail
xapi-project/xen-api pull request #4584
Opened 2021-11-29 08:02 UTC by liulinC

Ldap fails for cross domain if the target domain does not trust
the joined domain
Ldap is used to query user details like whether an account is
disabled, locked out etc, provide default value on failure

Signed-off-by: Lin Liu <lin.liu@citrix.com>

2021-11-29 08:30 UTC, liulinC commented
more discussions, see the internal CA ticket

2021-11-29 09:59 UTC, psafont commented
Can the query fail for other reasons? It doesn't look safe to be that the user query never fails anymore.

It seems to me that the code should request the joined domain for the user information, rather than the "target" one. Is that possible to do?

2021-11-29 14:13 UTC, edwintorok requested changes
It would be better to store the account_locked/account_expired as a tri-state instead of a boolean. E.g. a `bool option` would be good here:
* None - means we have no info whether the acocunt is locked or expired
* Some true - means we know for sure the account is locked/expired
* Some false - means we know for sure it isn't (at the time of the query)

Then each caller can determine how to handle the missing case and what the fallback would mean.

Alternatively move all the `account_disabled`, `account_locked`, `account_expired`, `password_expired` into an `extra_info` field, and make that an `extra_info option` type, again forcing each user to deal with the `None` case.

Then we can better review the impact of this change.

2021-11-29 15:09 UTC, psafont commented
Changing to a tristate is not that simple, it's stored as a map of string to strings which is exposed in the Auth module datamodel: https://github.com/xapi-project/xen-api/blob/master/ocaml/idl/datamodel.ml#L3111

2021-11-30 11:28 UTC, liulinC commented
> 

I tried to do that by set an N/A, but the session re-validate needs a bool to decide whether destroy the session, 
so let's just keep it for now, we will totally drop it in the future.

2021-11-30 13:01 UTC, psafont requested changes
This follows the design document:
1. on Lookup we stop using authenticated LDAP queries to time responses
2. on querying subject information, ldap is only used on the single-domain case, on multi-domain case, whether it's cross forest or not, the default value that doesn't invalidate sessions is used.

The second case might not be what we want, we need to make sure this new behaviour is not a regression from PBIS, this needs more discussion

2021-11-30 13:59 UTC, liulinC commented
> This follows the design document:
> 
> 1. on Lookup we stop using authenticated LDAP queries to time responses
> 2. on querying subject information, ldap is only used on the single-domain case, on multi-domain case, whether it's cross forest or not, the default value that doesn't invalidate sessions is used.
> 
> The second case might not be what we want, we need to make sure this new behaviour is not a regression from PBIS, this needs more discussion

This is not regression, 
PBIS cannot handle it even in simple domain/forest, see the discussion in the ticket.

2021-11-30 14:03 UTC, psafont approved these changes

2021-11-30 15:33 UTC, edwintorok commented
Not sure why the bool gets converted into a string when transferred through to xapi_session (and in `get_suspenion_value` it is then compared against `false`)

2021-11-30 15:51 UTC, edwintorok approved these changes

2021-12-01 10:56 UTC, liulinC commented
We probably does not need this any more as we are not sure whether winbind is the right solution to go to, 
but still merge this PR as
1. not affect other parts.
2. a little piece of refine, just in case we keep winbind in the future.

2021-12-01 10:56 UTC, merged