backport https://github.com/xapi-project/xen-api/pull/4646 to yangtze
xapi-project/xen-api pull request #4650
Opened 2022-03-13 03:46 UTC by liulinC

This is backport of  https://github.com/xapi-project/xen-api/pull/4646, target to Yangtze

2022-03-14 09:39 UTC, lindig approved these changes

2022-03-14 09:39 UTC, lindig commented on scripts/plugins/extauth-hook-AD.py
>      def _load_values(self):
I understand this is a packport but I notice a deeply nested logic that I don't trust to be correct. There are several special cases (empty lines, kv != 2) that are mostly unmotivated. Given that this code handles part of authentication I would like to see more clarity.

2022-03-14 10:27 UTC, psafont requested changes
Please add the hash of the original commits in the commit message of every commit, this makes it easier to see that the backport is accurate.

2022-03-15 10:57 UTC, psafont commented
The first commit is not a cherry-pick, it has additonal changes not present in the original commit. Is there a reason for this? If there are more commit backported please add each one as a cherry-pick.

The strategy with backport is to only import commits that are already on `master`, plus additional commits when some adaptations are needed to make it work on the branch

2022-03-15 12:50 UTC, liulinC commented
> Please add the hash of the original commits in the commit message of every commit, this makes it easier to see that the backport is accurate.

Just  updated, p

> The first commit is not a cherry-pick, it has additonal changes not present in the original commit. Is there a reason for this? If there are more commit backported please add each one as a cherry-pick.
> 
> The strategy with backport is to only import commits that are already on `master`, plus additional commits when some adaptations are needed to make it work on the branch

My autopep vim plugin updated it for me, I have just fixup, please help to take a look, thanks.

2022-03-15 13:58 UTC, psafont approved these changes
On the first commit a few more changes were added to match the final output of the patch.

Looks like a faithful backport to me.

2022-03-16 01:42 UTC, liulinC commented
> On the first commit a few more changes were added to match the final output of the patch.
> 
> Looks like a faithful backport to me.

The original commit do include a little pep8 fixup, see https://github.com/xapi-project/xen-api/pull/4646/commits/93dc7707fd4fa4de55a285ca9a179c3c1124ede0

That is caused by refine a little pep8 during the issue, then I put the remaining to a single commit.
I should squash the commits in master, but since it got merged, let's keep consistency here.

2022-03-16 01:45 UTC, merged