CP-39136: Reintroduce backend to vtpms
xapi-project/xen-api pull request #4707
Opened 2022-05-16 15:18 UTC by psafont

This type it's for signifying what persistence backend it's being used.
This means its type from a vm ref to an enum, for now with a single
possible value. There's no way to change yet backend, I would be wary of
adding them, as this is intended to permit several persistence backends
at the same time only for the benefit of developers.

2022-06-16 08:46 UTC, edwintorok reviewed
Have you checked that upgrades from the old DB work? Last I tried I got some errors from XAPI about missing backend field from the DB. Maybe it'd be better to leave the old `backend` field name alone (delete it if we have to) and add a `persistence_backend` field (to match the persistence_backend type), that way perhaps we'd have less issues during a DB upgrade. I think the schema minor vsn has to be bumped too, that is probably the upgrade wasn't working: without bumping the minor vsn XAPI won't know that it has to upgrade the DB (although perhaps we can improve that: we have a schema hash now, so XAPI could also check the schema hash of the DB it loads vs the one it got compiled with, and if it doens't match then run the DB upgrade anyway?)

2022-06-17 10:06 UTC, lindig approved these changes

2022-06-27 16:18 UTC, edwintorok requested changes
I think this requires a bump to the schema minor vsn to avoid problems with DB upgrades.

2022-07-07 10:35 UTC, closed without merging

2022-07-07 10:35 UTC, psafont commented
Will integrate this change into another PR