CP-40950: Make bias against scheduling vms on pool master configurable
xapi-project/xen-api pull request #4868
Opened 2022-12-09 16:30 UTC by YanRachel

By design, the pool master has a bias against scheduling VMs on it, preferring other member hosts.
An option to toggle this bias has been added, which can be used to improve performance, for example when the non-master hosts get overloaded.

2022-12-12 15:11 UTC, edwintorok approved these changes
Looks good, in the future we may want to switch the default to false once testing has shown that it is not needed anymore.
I think that the protection we have in Dom0 (with control-slice) against qemu taking away CPU from XAPI should be sufficient these days, but some pool bootstorm tests should give us some data on this.

2022-12-16 11:28 UTC, psafont requested changes
The approach seems fine, but a couple of red tape changes got outdated

2022-12-16 11:28 UTC, psafont commented on ocaml/idl/datamodel_lifecycle.ml
> -      Some "22.32.0-next"
This commit should be dropped, it's now included in the master branch

2022-12-16 11:28 UTC, psafont commented on ocaml/idl/datamodel_lifecycle.ml
> +  | "pool", "bias_enabled" ->
This change is out of date, 22.34.0 has been released. Please change it by removing changes in this file and rebuilding xapi

2022-12-19 08:47 UTC, psafont approved these changes

2022-12-19 12:22 UTC, YanRachel commented
Tested: https://info.citrite.net/display/~rachely/CP-40950+Notes

2023-01-09 13:47 UTC, merged