CA-375359 improve "pool_total_session_count" RRD description
xapi-project/xen-api pull request #4942
Opened 2023-03-22 14:41 UTC by lindig

The "pool_total_session_count" RRD is labeled incorrectly. The number reported is the change in the number of sessions since the previous sample was taken (which I believe was 5s agao). Change the name and description to

* pool_session_count_change
* "Change in number of sessions since last update"

2023-03-22 14:52 UTC, snwoods approved these changes

2023-03-22 15:03 UTC, psafont requested changes

2023-03-22 15:24 UTC, lindig commented
I've taken in the suggestions and squashed everything into a single commit.

2023-03-22 15:25 UTC, psafont commented on ocaml/xapi/xapi_stats.ml
>          ~min:0.0 ~units:"sessions" ()
Forgot to say, the unit needs to be changed as well, because it's a rate:
```suggestion
        ~min:0.0 ~units:"sessions per second" ()
```

2023-03-22 17:11 UTC, psafont approved these changes

2023-03-23 09:36 UTC, edwintorok approved these changes

2023-03-23 09:39 UTC, merged