CP-42019: Update wording for expiry message
xapi-project/xen-api pull request #5094
Opened 2023-07-10 10:18 UTC by gangj

As the suggested wording from Katherine are:
"Your Customer Success Services (CSS) agreement is expiring soon."
and "Your Customer Success Services (CSS) agreement has expired.",
remove the leading "The".

2023-07-10 10:34 UTC, liulinC approved these changes

2023-07-10 13:10 UTC, robhoes commented
The unit test failed, because the change also changes the TLS cert alerts. I think the right thing to do is to change the code that raises the certificate alerts such that the resulting message text is the same as before.

2023-07-11 02:18 UTC, gangj commented
> The unit test failed, because the change also changes the TLS cert alerts. I think the right thing to do is to change the code that raises the certificate alerts such that the resulting message text is the same as before.

Sorry for the test failure! Changed.

2023-07-11 08:25 UTC, psafont requested changes
Please squash the commtis

2023-07-11 09:55 UTC, merged