CA-381047: Increase max size limit to allow all tracing files to be e…
xapi-project/xen-api pull request #5181
Opened 2023-09-28 16:09 UTC by snwoods

…xtracted

2023-09-28 16:28 UTC, psafont approved these changes

2023-09-29 09:25 UTC, mg12 approved these changes

2023-09-29 09:54 UTC, mg12 requested changes

2023-09-29 09:54 UTC, mg12 commented on scripts/bugtool-plugin/xapi.xml
> +<capability pii="yes" max_size="1638400" max_time="60" mime="text/plain" checked="true"/>
It looks like this limit applies to all files in the directory together, not individual files: https://github.com/xenserver/status-report/blob/master/xen-bugtool#L517
So this limit is not enough for the up to 100MB of files in /var/log/dt. We either need to increase this value further, or create a new capability of max_size=100MB only for /var/log/dt

2023-09-29 09:56 UTC, lindig commented
Nit picking comment: the subject line could be made to fit: Increase bugtool size limit to <number>. RIght now one would wonder about the limit for that and its value.

2023-10-03 15:35 UTC, mg12 approved these changes

2023-10-04 09:04 UTC, merged