CA-392836,CA-392847: Not enforce power_state  in VM import
xapi-project/xen-api pull request #5632
Opened 2024-05-15 11:10 UTC by minglumlu

In some cases of VM import, the VM power state needs to be preserved. E.g. importing a suspended VM.
Actually, it's determined by the caller if the power state or some other attribute of a VM needs to be preserved or not.

2024-05-15 13:02 UTC, lindig reviewed
The code looks correct but the commit message could be improved. Specifically: on import maintain the power state and don't set it to Halted.

2024-05-16 13:46 UTC, psafont approved these changes
Now I'm wondering how the previous code with the license feature actually worked

2024-05-16 14:07 UTC, robhoes commented
Those two lines were added a few weeks ago in when replacing the function `create_from_record_without_checking_licence_feature_for_vendor_device` with just `create_from_record` a few line down in import.ml. And that function had:
```
let create_from_record_without_checking_licence_feature_for_vendor_device
    ~__context rpc session_id vm_record =
  (* vendor device is no longer licensed *)
  let mk_vm r =
    Client.Client.VM.create_from_record ~rpc ~session_id
      ~value:{r with API.vM_suspend_VDI= Ref.null; API.vM_power_state= `Halted}
  in
```
where `r` is the `vm_record` being passed in.

2024-05-16 14:13 UTC, robhoes requested changes
As above.

2024-05-17 02:29 UTC, minglumlu commented
> Those two lines were added a few weeks ago in [ebb58a8](https://github.com/xapi-project/xen-api/commit/ebb58a87387de3849e884e809cd4ace2dc83dd38) when replacing the function `create_from_record_without_checking_licence_feature_for_vendor_device` with just `create_from_record` a few line down in import.ml. And that function had:
> 
> ```
> let create_from_record_without_checking_licence_feature_for_vendor_device
>     ~__context rpc session_id vm_record =
>   (* vendor device is no longer licensed *)
>   let mk_vm r =
>     Client.Client.VM.create_from_record ~rpc ~session_id
>       ~value:{r with API.vM_suspend_VDI= Ref.null; API.vM_power_state= `Halted}
>   in
> ```
> 
> where `r` is the `vm_record` being passed in.
> 
> I think the problem is that the import code still needs the `vm_record` further down to check the original power state. But I don't think the change in this PR is correct; at least it won't revert to the behaviour before `ebb58a87387de3849e884e809cd4ace2dc83dd38`.
> 
> I think we need to use something like
> 
> ```
> { value with API.vM_suspend_VDI= Ref.null; API.vM_power_state= `Halted }
> ```
> 
> within the `let vm =` block where `create_from_record` is called.

Hi @robhoes  thanks. I see it now.
The new VM DB object is created with ```API.vM_suspend_VDI= Ref.null; API.vM_power_state= `Halted``` always.
The problem is the `vm_record.vM_power_state` and `vm_record.vM_suspend_VDI` should not be updated so that later they could be checked for updating the  new created VM DB record.
```
 676       (* Set the power_state and suspend_VDI if the VM is suspended.
 677                * If anything goes wrong, still continue if forced. *)
 678       if vm_record.API.vM_power_state = `Suspended then (
 679         try
 680           let vdi = (lookup vm_record.API.vM_suspend_VDI) state.table in
 681           Db.VM.set_power_state ~__context ~self:vm ~value:`Suspended ;
 682           Db.VM.set_suspend_VDI ~__context ~self:vm ~value:vdi ;
 683           let vm_metrics = Db.VM.get_metrics ~__context ~self:vm in
 684           Db.VM_metrics.set_current_domain_type ~__context ~self:vm_metrics
 685             ~value:vm_record.API.vM_domain_type
 686         with e ->
 687           if not config.force then (
 688             Backtrace.is_important e ;
 689             let msg =
 690               "Failed to find VM's suspend_VDI: "
 691               ^ Ref.string_of vm_record.API.vM_suspend_VDI
 692             in
 693             error "Import failed: %s" msg ;
 694             raise e
 695           )
```

2024-05-21 09:42 UTC, lindig approved these changes

2024-05-21 12:43 UTC, robhoes approved these changes

2024-05-21 12:43 UTC, merged