CP-49920: Moved power-on.py from scripts/poweron to python3/poweron directory.
xapi-project/xen-api pull request #5729
Opened 2024-06-25 12:31 UTC by ashwin9390

Main ticket CP-49100 :Move python3 scripts from scripts directory to python3 directory.

Sub task CP-49920:

- Modified Makefile to include  power-on.py under python3 directory
- Removed  power-on.py from scripts/Makefile
- Fixed No exception type(s) specified (bare-except)

Signed-off-by: Ashwinh <ashwin.h@cloud.com>

2024-06-25 12:43 UTC, psafont approved these changes

2024-06-25 17:22 UTC, bernhardkaindl requested changes

2024-06-25 17:22 UTC, bernhardkaindl commented on python3/poweron/power-on.py
> +            print(f"Exception occurred: {e}")
Some remarks:
- Errors should usually be logged to stderr, not stdout.
- We can log the type name of the exception
- There is no need to use an f-string, but of course you may if you really think that it is better.

```suggestion
            import sys
            print(type(e).__name__, " occured:", e, file=sys.stderr)
```

Of course:
- move the `import sys` to the top of the file, and
- run `isort` on the file to sort the imports.

Example for testing:
```py
import sys

try:
    raise OSError("Error message from the Exception")
except Exception as e:
    print(type(e).__name__, "occurred:", e, file=sys.stderr)
```

2024-06-26 11:30 UTC, bernhardkaindl approved these changes
The change of the exception handler looks good to me now, approving.

2024-06-26 11:34 UTC, merged