CP-49906: Moved extauth_hook_ad.py  scripts/plugins to python3/plugins directory
xapi-project/xen-api pull request #5796
Opened 2024-07-09 08:47 UTC by ashwin9390

Main ticket CP-49100 :Move python3 scripts from scripts directory to python3 directory.

Sub task CP-49906 
- Moved extauth-hook, test_extauth_hook_AD.py  and extauth-hook-AD.py
- Modified python3/Makefile to include these changes
- Removed extauth-hook and extauth-hook-AD from scripts/Makefile

Signed-off-by: Ashwinh <ashwin.h@cloud.com>

2024-07-09 09:02 UTC, bernhardkaindl approved these changes

2024-07-09 13:15 UTC, psafont approved these changes

2024-07-09 13:15 UTC, psafont requested changes
Needs a rebase

2024-07-09 13:17 UTC, bernhardkaindl approved these changes
@psafont Rebase done.

2024-07-10 09:06 UTC, psafont approved these changes

2024-07-10 09:07 UTC, psafont approved these changes

2024-07-10 09:07 UTC, merged