Python3 update feature merge
xapi-project/xen-api pull request #5896
Opened 2024-07-31 08:24 UTC by liulinC

FQP: https://info.citrite.net/display/engp/QA+Status+Page+for+Upgrade+PY2+To+PY3

2024-07-31 09:01 UTC, psafont commented
Some obsolete hashbangs are still present
```
pytype_reporter.py
1:#!/usr/bin/env python

python3/tests/test_usb_scan.py
1:#!/usr/bin/env python

ocaml/xcp-rrdd/scripts/rrdd/rrdd-example.py
1:#!/usr/bin/env python
```

Some python code remains in scripts:
```
$ file scripts/**/* | grep Python
scripts/examples/python/XenAPI/__init__.py:                  Python script, ASCII text executable
scripts/examples/python/XenAPI/XenAPI.py:                    Python script, ASCII text executable
scripts/examples/python/XenAPIPlugin.py:                     Python script, ASCII text executable
scripts/xc.py:                                               Python script, ASCII text executable
scripts/yum-plugins/accesstoken.py:                          Python script, ASCII text executable
scripts/yum-plugins/ptoken.py:                               Python script, ASCII text executable
```
The XenAPI library needs to be relocated and drop python2 support

scripts/xc.py looks like it can be removed

the yum-plugins should be already python3 and should be a simple move

2024-07-31 09:03 UTC, stephenchengCloud commented on scripts/examples/python/XenAPI/XenAPI.py
> +import errno
Raise a PR to featue/py3 to fix this:
https://github.com/xapi-project/xen-api/pull/5897

2024-07-31 09:30 UTC, liulinC commented
> yum

yum-plugins is NOT python3, as yum is python2 only.  
XS8/xapi still use yum to do updates,  so it has to be python2. 

About XenAPI.py,  it is not py2-3 compatible, and provides python2/3 SDK for xapi clients.
AFAICT, ourself is py2 free and we only use our python3 SDK.

However, we are NOT sure how our customer making use of it.
If any customer using python2 SDK, drop python2 support will break customer usage.
@psafont  does this make sense to you?

2024-07-31 10:23 UTC, psafont commented
> yum-plugins is NOT python3, as yum is python2 only

Sorry, I confused yum for dnf, I understand that the yum's python2 code can only be removed once dnf is used

> However, we are NOT sure how our customer making use of it.
> If any customer using python2 SDK, drop python2 support will break customer usage.
I 
I understand not wanting to break existing users, but python2 has long been out of support. At least for XS9 I'd like to remove support

2024-07-31 11:00 UTC, stephenchengCloud commented
- Removed xc.py
- Use python3 shebang for pytype_reporter.py and test_usb_scan.py

Raised a PR to feature/py3 branch: 
https://github.com/xapi-project/xen-api/pull/5899

2024-07-31 11:40 UTC, stephenchengCloud commented
- Convert rrdd-example.py to python3
Raised a PR to feature/py3 branch:
https://github.com/xapi-project/xen-api/pull/5900

2024-07-31 11:51 UTC, stephenchengCloud commented
> > However, we are NOT sure how our customer making use of it.
> > If any customer using python2 SDK, drop python2 support will break customer usage.
> 
> I understand not wanting to break existing users, but python2 has long been out of support. At least for XS9 I'd like to remove support

**Now only one issue is left: Should we drop python2 support for XenAPI (just for XS8, as XS9 only supports python3)?**
Note that, for these XenAPI scripts, the code is compatible with py2 and py3.
Also involve @edwintorok here, because I saw he made changes to XenAPI.py recently.

2024-08-01 02:01 UTC, liulinC commented
> > yum-plugins is NOT python3, as yum is python2 only
> 
> Sorry, I confused yum for dnf, I understand that the yum's python2 code can only be removed once dnf is used

Thanks for confirm this,  in this case, we will just keep the yum plugins as it is.

> > However, we are NOT sure how our customer making use of it.
> > If any customer using python2 SDK, drop python2 support will break customer usage.
> 
> I understand not wanting to break existing users, but python2 has long been out of support. At least for XS9 I'd like to remove support
It make sense to clean all python2 code for XS9.  
However, in this repo, we got master code compatible for XS8 and XS9 ( and I think it is a good option to avoid frequently branch sync, we xapi update very frequently).   There maybe two possible solutions:
- Make a copy of XenAPI and pure py3.  This means we have to duplicate the codes in this repo and sync fixes between the copy. This should be avoided.
- XenAPI code be py2-py3 compatible.  This is the right option we currently take.
Hope this make sense to you.

2024-08-02 04:23 UTC, stephenchengCloud commented
- Drop python2 support for XenAPI
Raised a PR to feature/py3 branch:
https://github.com/xapi-project/xen-api/pull/5903

Tested:
202272 Ring3 BST+BVT (One failed case due to a known issue)
202275 ToolStack Input Karma (passed)
202276 Storage BST (passed, one failed case due to environmental issue, re-run it in 4066324)
4066324 XFSSmokeTest

2024-08-02 13:58 UTC, psafont commented
The CI must also be changed to remove all python2-related actions. This includes the use of BUILD_PY2 in `.github/workflows/main.yml` and the python2-specific action in `workflows/setup-xapi-environment/action.yml`

2024-08-03 03:08 UTC, stephenchengCloud commented
- Remove python2 related CI actions
Raised a PR to feature/py3 branch: 
https://github.com/xapi-project/xen-api/pull/5908

There code has already been tested by python3.
```
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.3.2, pluggy-1.5.0 -- /home/runner/.cache/pre-commit/repom96bpdxe/py_env-**python3.11/bin/python**
cachedir: .pytest_cache
rootdir: /home/runner/work/xen-api/xen-api
configfile: pyproject.toml
testpaths: python3, **ocaml/xcp-rrdd, ocaml/xenopsd**

.....

ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[None-5-reading0-5] PASSED [ 87%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[1-5-reading1-5] PASSED [ 88%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[2.25-5-reading2-3.75] PASSED [ 89%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[0.5-30-reading3-30] PASSED [ 90%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[2-120-reading4-120] PASSED [ 91%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[11-5-reading5-0] PASSED [ 91%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[1-10-reading6-0] PASSED [ 92%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[1-9-reading7-9] PASSED [ 93%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[1-10-reading8-8] PASSED [ 94%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_params[1-7-reading9-5] PASSED [ 95%]
ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py::test_api_getter_functions PASSED [ 95%]
ocaml/xenopsd/scripts/test_igmp_query_injector.py::TestXSWatcher::test_unwatch PASSED [ 96%]
ocaml/xenopsd/scripts/test_igmp_query_injector.py::TestXSWatcher::test_watch PASSED [ 97%]
ocaml/xenopsd/scripts/test_igmp_query_injector.py::TestIGMPQueryInjector::test_inject_with_connection_state_check_succ PASSED [ 98%]
ocaml/xenopsd/scripts/test_igmp_query_injector.py::TestIGMPQueryInjector::test_inject_with_connection_state_check_timeout PASSED [ 99%]
ocaml/xenopsd/scripts/test_igmp_query_injector.py::TestIGMPQueryInjector::test_inject_without_connection_state_check PASSED [100%]
...
Name                                                Stmts   Miss  Cover
-----------------------------------------------------------------------
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py                   171     83    51%
ocaml/xenopsd/scripts/igmp_query_injector.py          144     51    65%
ocaml/xenopsd/scripts/test_igmp_query_injector.py      73      1    99%
```

2024-08-06 05:58 UTC, gangj approved these changes

2024-08-07 08:27 UTC, edwintorok commented
There is a TODO in pyproject.toml about xapi-storage, that can probably be commented out.

2024-08-07 08:29 UTC, edwintorok commented
There are also 2 python2 type checks that can probably be dropped:
```
ocaml/xapi-storage/python/xapi/__init__.py:if sys.version_info[0] > 2:
python3/libexec/mail-alarm:        if sys.version_info.major == 2:
```

2024-08-07 08:37 UTC, edwintorok commented
With this change pytype finds a few more bugs:
```
diff --git a/pyproject.toml b/pyproject.toml
index 8a7ca2dc9..1fabccd06 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -294,14 +294,11 @@ inputs = [
     # Python 3
     "python3/",
     "ocaml/xcp-rrdd",
-
-    # To be added later,
-    # when converted to Python3-compatible syntax:
-    # "ocaml/xapi-storage/python",
+    "ocaml/xenopsd",
+    "ocaml/xapi-storage/python",
+    "ocaml/vhd-tool"
 ]
 disable = [
-    # Reduce noise from python2 scripts(import yum, xenfsimage, xcp, urlgrabber)
-    "import-error",
 ]
 platform = "linux"
 # Allow pytype to find the XenAPI module, the rrdd module and python3 modules:
```

```
=============================== warnings summary ===============================
ocaml/xenopsd/scripts/test_igmp_query_injector.py::TestIGMPQueryInjector::test_inject_with_connection_state_check_timeout
  /home/edvint/.cache/pre-commit/repokai84mwg/py_env-python3.11/lib/python3.11/site-packages/_pytest/threadexception.py:82: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-2 (check_and_inject)

  Traceback (most recent call last):
    File "/usr/lib64/python3.11/threading.py", line 1045, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.11/threading.py", line 982, in run
      self._target(*self._args, **self._kwargs)
    File "/home/edvint/koji/py3/xen-api/ocaml/xenopsd/scripts/igmp_query_injector.py", line 77, in check_and_inject
      path, vif = watcher.read_watch()
      ^^^^^^^^^
  ValueError: not enough values to unpack (expected 2, got 0)

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

2024-08-07 08:38 UTC, edwintorok commented
Is the python typing info for xs lowlevel slightly wrong?

2024-08-07 08:43 UTC, edwintorok commented
There are 51 errors/warnings reported with that change:
```
#### pytype_reporter extracted 51 problem reports from pytype output
|    | Location                                                                                                                                                              | Error code                                                                     | Error message                                                                                     | Function      | Error description                                              |
|---:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------|:--------------|:---------------------------------------------------------------|
|  0 | [`test_api_wait_until_next_reading:13`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py#L13) | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'rrdd'<br>Can't find module 'rrdd'.                                             | `<module>`    | nan                                                            |
|  1 | [`echo:6`](https://github.com/xapi-project/xen-api/blob/feature/py3/python3/plugins/echo.py#L6)                                                                       | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'XenAPIPlugin'<br>Can't find module 'XenAPIPlugin'.                             | `<module>`    | nan                                                            |
|  2 | [`restore-sr-metadata:12`](https://github.com/xapi-project/xen-api/blob/feature/py3/python3/libexec/restore-sr-metadata.py#L12)                                       | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'XenAPI'<br>Can't find module 'XenAPI'.                                         | `<module>`    | nan                                                            |
|  3 | [`sr:25`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py#L25)              | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'xapi'<br>Can't find module 'xapi'.                                             | `<module>`    | nan                                                            |
|  4 | [`sr:26`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py#L26)              | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'xapi'<br>Can't find module 'xapi'.                                             | `<module>`    | nan                                                            |
|  5 | [`sr:27`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py#L27)              | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'xapi.storage'<br>Can't find module 'xapi.storage'.                             | `<module>`    | nan                                                            |
|  6 | [`sr:28`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py#L28)              | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'xapi.storage.common'<br>Can't find module 'xapi.storage.common'.               | `<module>`    | nan                                                            |
|  7 | [`sr:29`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py#L29)              | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'xapi.storage.api.v5.volume'<br>Can't find module 'xapi.storage.api.v5.volume'. | `<module>`    | nan                                                            |
|  8 | [`sr:31`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xapi-storage/python/examples/volume/org.xen.xapi.storage.simple-file/sr.py#L31)              | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'volume'<br>Can't find module 'volume'.                                         | `<module>`    | nan                                                            |
|  9 | [`wlan:10`](https://github.com/xapi-project/xen-api/blob/feature/py3/python3/poweron/wlan.py#L10)                                                                     | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'inventory'<br>Can't find module 'inventory'.                                   | `<module>`    | nan                                                            |
| 10 | [`wlan:11`](https://github.com/xapi-project/xen-api/blob/feature/py3/python3/poweron/wlan.py#L11)                                                                     | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'xcp'<br>Can't find module 'xcp'.                                               | `<module>`    | nan                                                            |
| 11 | [`wlan:12`](https://github.com/xapi-project/xen-api/blob/feature/py3/python3/poweron/wlan.py#L12)                                                                     | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'XenAPIPlugin'<br>Can't find module 'XenAPIPlugin'.                             | `<module>`    | nan                                                            |
| 12 | [`igmp_query_injector:6`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xenopsd/scripts/igmp_query_injector.py#L6)                                   | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'scapy.all'<br>Can't find module 'scapy.all'.                                   | `<module>`    | nan                                                            |
| 13 | [`igmp_query_injector:7`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xenopsd/scripts/igmp_query_injector.py#L7)                                   | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'scapy.contrib.igmp'<br>Can't find module 'scapy.contrib.igmp'.                 | `<module>`    | nan                                                            |
| 14 | [`igmp_query_injector:8`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xenopsd/scripts/igmp_query_injector.py#L8)                                   | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'xcp'<br>Can't find module 'xcp'.                                               | `<module>`    | nan                                                            |
| 15 | [`igmp_query_injector:11`](https://github.com/xapi-project/xen-api/blob/feature/py3/ocaml/xenopsd/scripts/igmp_query_injector.py#L11)                                 | [import-error](https://google.github.io/pytype/errors.html#import-error)       | Can't find module 'xen.lowlevel.xs'<br>Can't find module 'xen.lowlevel.xs'.                       | `<module>`    | nan                                                            |
| 16  [...]

2024-08-07 08:45 UTC, edwintorok requested changes
Some python files were excluded from `pytype` checks.
Now that everything has been converted to python3, we need to enable the checks on all those files and fix the problems.

There are 11 errors reported, we should check whether they are real errors and fix them

2024-08-08 17:01 UTC, edwintorok commented
There is a conflict with scripts/plugins/openvswitch-config-update, I suggest opening a PR to merge master into `feature/py3` to solve it.

2024-08-08 17:35 UTC, bernhardkaindl commented
> There is a conflict with `scripts/plugins/openvswitch-config-update`, I suggest opening a PR to merge master into `feature/py3` to solve it.

Yes, the merge of https://github.com/xapi-project/xen-api/pull/5918/files needs to be merged into feature/py3 before it can be merged.

The updated `feature/py3` branch includes the merges of #5921 and #5923 that fix the `pytype` warnings that were requested to be fixed above.

2024-08-14 06:38 UTC, liulinC commented
New nightly result: 
Details, refer to internal nightly report,

Suite/Seq | Suite/Seq ID | Build | Date | Pass Rate | Notes
-- | -- | -- | -- | -- | --
Misc2hostXSConsoleTC15296PV-ShimSecWE | 40762584076260407626140762624076138 | pbb-linl-xs8/235428 | 13 Aug 2024 | 100% | The build with py2 XenAPI.py in xapi.spec. Performed all the failed tests in CA-397267 - No module named XenAPI as /usr/bin/eliloader is still python2 In Review and the jobs are all passed.
Core: Nightly | 202744 | pb-linl-xs8/202744 | 11 Aug 2024 | 97.6% | The build is without py2 XenAPI.py. Triage complete. Found one related issue CA-397267 - No module named XenAPI as /usr/bin/eliloader is still python2 In Review which is caused by the py2 XenAPI.py is removed.
Ring3: BVT | 202806 | pb-linl-xs8/202744 | 11 Aug 2024 | 100% | The build is without py2 XenAPI.py
Ring3: BST | 202805 | pb-linl-xs8/202744 | 11 Aug 2024 | 99.4% | The build is without py2 XenAPI.py. Known issue in xapi master branch CA-397268
ToolStack-Input: Karma Tests | 202807 | pb-linl-xs8/202744 | 11 Aug 2024 | 100% | The build is without py2 XenAPI.py
Networking: IP Multicase | 202809 | pb-linl-xs8/202744 | 11 Aug 2024 | 92.0% | Found CA-397459 - The multicast traffic is not found as expected New which occurred in rt-next as well

Misc2host

XSConsole

TC15296

PV-Shim

SecWE

4076258

4076260

4076261

4076262

4076138

pbb-linl-xs8/235428	
13 Aug 2024 

100%	
The build with py2 XenAPI.py in xapi.spec. 

Performed all the failed tests in CA-397267 - No module named XenAPI as /usr/bin/eliloader is still python2 In Review and the jobs are all passed.

Core: Nightly	202744	pb-linl-xs8/202744 	
11 Aug 2024 

97.6%	
The build is without py2 XenAPI.py. 

Triage complete. Found one related issue [CA-397267](https://issues.citrite.net/browse/CA-397267) - No module named XenAPI as /usr/bin/eliloader is still python2 In Review which is caused by the py2 XenAPI.py is removed.

Ring3: BVT	202806	pb-linl-xs8/202744 	
11 Aug 2024 

100%	
The build is without py2 XenAPI.py

Ring3: BST	202805	pb-linl-xs8/202744 	
11 Aug 2024 

99.4%	
The build is without py2 XenAPI.py. Known issue in xapi master branch CA-397268 

ToolStack-Input: Karma Tests	202807	pb-linl-xs8/202744 	
11 Aug 2024 

100%	
The build is without py2 XenAPI.py

Networking: IP Multicase	202809	pb-linl-xs8/202744 	
11 Aug 2024 

92.0%	
Found CA-397459 - The multicast traffic is not found as expected New which occurred in rt-next as well

2024-08-19 09:09 UTC, lindig approved these changes
Can we have @bernhardkaindl  take a look?

2024-08-19 12:24 UTC, psafont approved these changes
Almost all the python2 usage has been removed.

Only a few invocations of `python` remain:

- a snippet in `scripts/generate-iscsi-iqn`
- a snippet in `scripts/xe-restore-metadata` and `scripts/xe-backup-metadata`
- ocaml/message-switch/core_test/interop-test.sh invokes a non-existing python file. The file should be removed altogether, it's not used.

Since they seem to be python3-compatible, and on XS9 `python` will be aliased to python3, it doesn't seem like a blocker.

2024-08-20 07:33 UTC, liulinC commented
> Almost all the python2 usage has been removed.
> 
> Only a few invocations of `python` remain:
> 
> * a snippet in `scripts/generate-iscsi-iqn`
> * a snippet in `scripts/xe-restore-metadata` and `scripts/xe-backup-metadata`
> * ocaml/message-switch/core_test/interop-test.sh invokes a non-existing python file. The file should be removed altogether, it's not used.
> 
> Since they seem to be python3-compatible, and on XS9 `python` will be aliased to python3, it doesn't seem like a blocker.

- The minor issues are fixed by PR https://github.com/xapi-project/xen-api/pull/5944, although it is low risk, some XenRT test is run and result updated in that PR
- `xe-backup-metadata` and `xe-restore-metadata` comments it can be refined by `uuidgen`, @lindig  Feel free to refine after this PR got merged.

2024-08-20 07:34 UTC, liulinC commented
Note:  This PR need to merge together with the PR in the spec repo.

2024-09-04 09:12 UTC, lindig commented
Can we rebase this branch; I'll merge it next

2024-09-04 10:16 UTC, merged